// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        CreateDialog: typeof import('./src/components/createDialog/index.vue')['default'];
        CustomSchemaTemplateSet: typeof import('./src/components/custom-schema-template-set/index.vue')['default'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElDialog: typeof import('element-plus/es')['ElDialog'];
        ElEmpty: typeof import('element-plus/es')['ElEmpty'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElOption: typeof import('element-plus/es')['ElOption'];
        ElRadio: typeof import('element-plus/es')['ElRadio'];
        ElSelect: typeof import('element-plus/es')['ElSelect'];
        GitControl: typeof import('./src/components/global/gitControl.vue')['default'];
        HomeCover: typeof import('./src/components/saveDialog/homeCover.vue')['default'];
        PhoneCtn: typeof import('./src/components/global/phoneCtn.vue')['default'];
        QrDialog: typeof import('./src/components/qrDialog/index.vue')['default'];
        RealTimeView: typeof import('./src/components/realTimeView/index.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        SaveDialog: typeof import('./src/components/saveDialog/index.vue')['default'];
        TopBar: typeof import('./src/components/topBar/index.vue')['default'];
    }
    export interface ComponentCustomProperties {
        vLoading: typeof import('element-plus/es')['ElLoadingDirective'];
    }
}
