// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CMiniMCE: typeof import('./src/components/cMiniMCE/index.vue')['default']
    ConfigCtn: typeof import('./src/components/global/configCtn.vue')['default']
    ConfigItem: typeof import('./src/components/global/configItem.vue')['default']
    ConfigWrap: typeof import('./src/components/global/configWrap.vue')['default']
    Control: typeof import('./src/components/control/index.vue')['default']
    ControlConfig: typeof import('./src/components/control/controlConfig.vue')['default']
    ControlPanel: typeof import('./src/components/control/controlPanel.vue')['default']
    ControlWidgets: typeof import('./src/components/control/controlWidgets.vue')['default']
    ControlWidgetShape: typeof import('./src/components/control/controlWidgetShape.vue')['default']
    CreateDialog: typeof import('./src/components/createDialog/index.vue')['default']
    CTinymce: typeof import('./src/components/cTinymce/index.vue')['default']
    CustomSchemaTemplateSet: typeof import('./src/components/custom-schema-template-set/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    GitControl: typeof import('./src/components/global/gitControl.vue')['default']
    HomeCover: typeof import('./src/components/saveDialog/homeCover.vue')['default']
    ModelsList: typeof import('./src/components/modelsList/index.vue')['default']
    NavBar: typeof import('./src/components/navBar/index.vue')['default']
    PhoneCtn: typeof import('./src/components/global/phoneCtn.vue')['default']
    QrDialog: typeof import('./src/components/qrDialog/index.vue')['default']
    RealTimeView: typeof import('./src/components/realTimeView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveDialog: typeof import('./src/components/saveDialog/index.vue')['default']
    SearchBar: typeof import('./src/components/searchBar/index.vue')['default']
    SideBar: typeof import('./src/components/sideBar/index.vue')['default']
    TopBar: typeof import('./src/components/topBar/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
